<?php

namespace Arnm\ContactBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RequestTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestTypeRepository extends EntityRepository
{
}
